name: Count Lines of Code

on:
  push:
    branches:
      - "*"

jobs:
  cloc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Count Lines of Code (cloc)
        uses: djdefi/cloc-action@6
